# stubs/minivec_cpp.pyi
from typing import Any, List
import numpy as np
# np.array of float values

def l2(a: np.ndarray, b: np.ndarray) -> np.float32: ...
def l2_squared(a: np.ndarray, b: np.ndarray) -> np.float32: ...

class HNSWIndex:
    entry_point: int
    max_level: int

    def __init__(self, M: int = 16) -> None: ...
    def random_level(self) -> int: ...
    def add_node(self, vec: Any) -> int: ...
    def greedy_search_layer(self, query: Any, entry_id: int, layer: int) -> int: ...
    def ef_search(self, query: Any, entry_id: int, ef: int, k: int) -> List[int]: ...
